[build]
    command = "ng build && ng run foodapptemp:server"  # Ensure this matches the build script you're using
    publish = "dist/foodapptempbackend/browser"
    functions = "netlify/functions"
